import { StyleSheet } from "react-native";
import { palette, radius, space } from "../tokens";
import { ThemeMode } from "../theme";

export const getChatBotStyles = (t: ThemeMode, isDark: boolean) => {
  const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: t.bg },
    keyboardView: { flex: 1 },
    header: {
      backgroundColor: isDark ? t.surface : t.accentBar,
      paddingHorizontal: space[4],
      paddingVertical: space[4],
      borderBottomWidth: 1,
      borderBottomColor: t.cardBorder,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: space[2],
    },
    headerBackText: { fontSize: 13, color: isDark ? t.muted : t.overlayLight },
    headerTitle: { fontSize: 20, fontWeight: "bold", color: isDark ? t.text : palette.white },
    headerSubtitle: { fontSize: 13, color: isDark ? t.muted : t.overlayLight },
    themeToggle: {
      width: 36,
      height: 36,
      borderRadius: radius.full,
      backgroundColor: t.avatarBg,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: t.cardBorder,
    },
    messageBubbleUser: {
      marginVertical: space[1],
      maxWidth: "80%",
      alignSelf: "flex-end",
      borderRadius: radius.lg,
      borderBottomRightRadius: space[1],
      backgroundColor: t.accentBar,
      paddingHorizontal: space[4],
      paddingVertical: space[3],
    },
    messageBubbleBot: {
      marginVertical: space[1],
      maxWidth: "80%",
      alignSelf: "flex-start",
      borderRadius: radius.lg,
      borderBottomLeftRadius: space[1],
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.cardBorder,
      paddingHorizontal: space[4],
      paddingVertical: space[3],
    },
    messageTextUser: { fontSize: 15, lineHeight: 20, color: palette.white },
    messageTextBot: { fontSize: 15, lineHeight: 20, color: t.text },
    suggestionsWrap: { paddingHorizontal: space[4], paddingBottom: space[2] },
    suggestionsLabel: { marginBottom: space[2], fontSize: 12, color: t.muted },
    suggestionsRow: { flexDirection: "row", flexWrap: "wrap", gap: space[2] },
    suggestionChip: {
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: t.accentBar,
      backgroundColor: t.surface,
      paddingHorizontal: space[3],
      paddingVertical: space[1],
    },
    suggestionChipText: { fontSize: 12, color: t.accentBar },
    inputBar: {
      flexDirection: "row",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: t.cardBorder,
      backgroundColor: t.surface,
      paddingHorizontal: space[3],
      paddingVertical: space[2],
    },
    textInput: {
      flex: 1,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: t.inputBorder,
      backgroundColor: t.bg,
      paddingHorizontal: space[4],
      paddingVertical: space[2],
      fontSize: 15,
      color: t.text,
    },
    sendButton: {
      marginLeft: space[2],
      width: 40,
      height: 40,
      borderRadius: radius.full,
      backgroundColor: t.accentBar,
      alignItems: "center",
      justifyContent: "center",
    },
    sendButtonText: { fontSize: 18, fontWeight: "bold", color: palette.white },
  });

  return styles;
};
