import { StyleSheet } from "react-native";
import { ThemeMode } from "../theme";

export const getChatBotStyles = (t: ThemeMode, isDark: boolean) => {
  const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: t.bg },
    keyboardView: { flex: 1 },
    header: {
      backgroundColor: isDark ? t.surface : t.accentBar,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: t.cardBorder,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    headerBackText: { fontSize: 13, color: isDark ? t.muted : "rgba(255,255,255,0.7)" },
    headerTitle: { fontSize: 20, fontWeight: "bold", color: isDark ? t.text : "#ffffff" },
    headerSubtitle: { fontSize: 13, color: isDark ? t.muted : "rgba(255,255,255,0.8)" },
    themeToggle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: t.avatarBg,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: t.cardBorder,
    },
    messageBubbleUser: {
      marginVertical: 4,
      maxWidth: "80%",
      alignSelf: "flex-end",
      borderRadius: 16,
      borderBottomRightRadius: 4,
      backgroundColor: t.accentBar,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    messageBubbleBot: {
      marginVertical: 4,
      maxWidth: "80%",
      alignSelf: "flex-start",
      borderRadius: 16,
      borderBottomLeftRadius: 4,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.cardBorder,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    messageTextUser: { fontSize: 15, lineHeight: 20, color: "#ffffff" },
    messageTextBot: { fontSize: 15, lineHeight: 20, color: t.text },
    suggestionsWrap: { paddingHorizontal: 16, paddingBottom: 8 },
    suggestionsLabel: { marginBottom: 8, fontSize: 12, color: t.muted },
    suggestionsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    suggestionChip: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: t.accentBar,
      backgroundColor: t.surface,
      paddingHorizontal: 12,
      paddingVertical: 4,
    },
    suggestionChipText: { fontSize: 12, color: t.accentBar },
    inputBar: {
      flexDirection: "row",
      alignItems: "center",
      borderTopWidth: 1,
      borderTopColor: t.cardBorder,
      backgroundColor: t.surface,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    textInput: {
      flex: 1,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: t.cardBorder,
      backgroundColor: t.bg,
      paddingHorizontal: 16,
      paddingVertical: 8,
      fontSize: 15,
      color: t.text,
    },
    sendButton: {
      marginLeft: 8,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.accentBar,
      alignItems: "center",
      justifyContent: "center",
    },
    sendButtonText: { fontSize: 18, fontWeight: "bold", color: "#ffffff" },
  });

  return styles;
};
