export const rootStyles = {
  screen: "flex-1 bg-app-bg p-5",
  card: "rounded-xl bg-app-surface p-4 shadow-card",
  title: "text-[22px] font-bold text-app-text",
  subtitle: "text-[16px] font-semibold text-app-text",
  muted: "text-app-muted",
  input: "rounded-lg border border-[#9ca3af] bg-white px-3 py-3 text-[16px] text-app-text placeholder:text-[#4b5563]",
  pickerWrap: "mb-3 rounded-lg border border-app-border bg-app-surface",
  rowBetween: "flex-row items-center justify-between",
  buttonPrimary: "items-center rounded-lg bg-blue-500 p-[14px]",
  buttonSecondary: "items-center rounded-lg border border-app-border bg-white p-[14px]",
  buttonPrimaryText: "font-semibold text-white",
  buttonSecondaryText: "font-semibold text-app-text",
  loadingScreen: "flex-1 items-center justify-center bg-app-bg p-5",
  errorText: "mb-[14px] text-[#c62828]",
  notificationCardRead: "mb-[10px] rounded-lg border border-app-border bg-[#f5f5f5] p-3",
  notificationCardUnread: "mb-[10px] rounded-lg border border-app-border bg-[#e3f2fd] p-3",
  paginationMeta: "text-[14px] text-[#374151]",
  paginationButtonEnabled: "rounded-lg bg-blue-500 px-4 py-2",
  paginationButtonDisabled: "rounded-lg bg-[#cbd5e1] px-4 py-2",
} as const;
