export const rootStyles = {
  screen:           "flex-1 bg-app-bg p-5",
  card:             "rounded-app-lg bg-app-surface p-4 shadow-card",
  title:            "text-app-xl font-bold text-app-text",
  subtitle:         "text-app-md font-semibold text-app-text",
  muted:            "text-app-muted",
  input:            "rounded-app-md border border-app-input-border bg-app-surface px-3 py-3 text-app-base text-app-text placeholder:text-app-placeholder",
  pickerWrap:       "mb-3 rounded-app-md border border-app-border bg-app-surface",
  rowBetween:       "flex-row items-center justify-between",
  buttonPrimary:    "items-center rounded-app-lg bg-app-primary p-[14px]",
  buttonSecondary:  "items-center rounded-app-lg border border-app-border bg-app-surface p-[14px]",
  buttonPrimaryText:   "font-semibold text-white",
  buttonSecondaryText: "font-semibold text-app-text",
  loadingScreen:    "flex-1 items-center justify-center bg-app-bg p-5",
  errorText:        "mb-[14px] text-app-error",
  notificationCardRead:   "mb-[10px] rounded-app-md border border-app-border bg-app-bg-muted p-3",
  notificationCardUnread: "mb-[10px] rounded-app-md border border-app-border bg-app-primary-bg p-3",
  paginationMeta:          "text-app-sm text-app-text-secondary",
  paginationButtonEnabled: "rounded-app-md bg-app-primary px-4 py-2",
  paginationButtonDisabled:"rounded-app-md bg-app-disabled px-4 py-2",
} as const;
